### PR TITLE
Correction in execution node project deliverables

### PR DESCRIPTION
**Pull request by rajat503**

### CODE REVIEW

**Comment by prasadtalasila** [comment]
@rajat503 Why wouldn't you want to have feature compatibility with the existing execution nodes?

**Comment by rajat503** [comment]
@prasadtalasila I'm still not sure about why execution node should have the functions of the load balancer.

**Comment by prasadtalasila** [comment]
MY BAD. The statement is supposed to read as:    
Has all the functions of the existing execution node.

**Comment by prasadtalasila** [comment]
I updated the master with the correction. There is no need for this PR anymore. Thanks for bringing it up.

**Pull request closed without merging**
